apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-ac
  labels:
    app: redis-ac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-ac
  template:
    metadata:
      labels:
        app: redis-ac
    spec:
      containers:
      - name: redis-ac
        image: redis
        ports:
        - containerPort: 6379