apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-redis-serveur
  labels:
    app: ac-redis-serveur
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ac-redis-serveur
  template:
    metadata:
      labels:
        app: ac-redis-serveur
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: ac-redis-serveur
        image: cloud.canister.io:5000/arhturescriou/node-redis
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: REDIS_URL
          value: "redis://10.2.4.2"